import { useEffect, useRef } from 'react';
import { ALERT_TYPES } from '../config/alertTypes';
import { getZone } from '../config/factoryZones';
import { SEVERITY_META } from '../config/severity';
import type { AlertSource, FactoryAlert } from '../types/alerts';
import { formatConfidence, formatDate, formatTime } from '../utils/format';
import { gridRef } from '../utils/grid';
import { SeverityBadge } from './SeverityBadge';
import { IconCheck, IconClose, IconTarget } from './icons';

interface AlertDetailsProps {
  alert: FactoryAlert | null;
  onClose: () => void;
  onAcknowledge: (alertId: string) => void;
  onShowOnMap: (alertId: string) => void;
}

const DETECTION_LABEL: Record<AlertSource, string> = {
  simulation: 'Manual Simulation',
  ml: 'ML anomaly model (live feed)',
  external: 'External system',
};

/** Slide-over drawer with the full (simulated) alert record. */
export function AlertDetails({ alert, onClose, onAcknowledge, onShowOnMap }: AlertDetailsProps) {
  const closeRef = useRef<HTMLButtonElement>(null);
  const open = alert !== null;

  // Focus management + Escape to close.
  useEffect(() => {
    if (!open) return;
    const previous = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    closeRef.current?.focus();
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        event.stopPropagation();
        onClose();
      }
    };
    window.addEventListener('keydown', onKey, true);
    return () => {
      window.removeEventListener('keydown', onKey, true);
      previous?.focus();
    };
  }, [open, onClose]);

  if (!alert) return null;

  const zone = getZone(alert.zoneId);
  const typeDefinition = ALERT_TYPES[alert.type];
  const simulated = alert.source === 'simulation';

  return (
    <div className="drawer-root">
      <div className="drawer-backdrop" onClick={onClose} aria-hidden="true" />
      <aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title" data-severity={alert.severity}>
        <header className="drawer__head">
          <div>
            <span className="eyebrow">Alert details</span>
            <h2 id="drawer-title" className="num">
              {alert.id}
            </h2>
          </div>
          <button ref={closeRef} type="button" className="icon-btn" onClick={onClose} aria-label="Close details">
            <IconClose size={20} />
          </button>
        </header>

        <div className="drawer__scroll">
          <div className="sim-banner" data-live={!simulated || undefined}>
            <strong>{simulated ? 'Simulated data' : 'Prototype feed'}</strong>
            <span>
              {simulated
                ? 'Generated by the alert simulator for demonstration. Not connected to live equipment.'
                : 'Received from the configured alert stream. Values shown as delivered.'}
            </span>
          </div>

          <div className="drawer__summary">
            <SeverityBadge severity={alert.severity} size="lg" muted={alert.acknowledged} />
            <span className="drawer__type">{typeDefinition.label}</span>
            <span className="status-pill" data-ack={alert.acknowledged || undefined}>
              {alert.acknowledged ? 'ACKNOWLEDGED' : 'ACTIVE'}
            </span>
          </div>
          <p className="drawer__desc">{alert.description}</p>

          <dl className="detail-grid">
            <div>
              <dt>Alert ID</dt>
              <dd className="num">{alert.id}</dd>
            </div>
            <div>
              <dt>Equipment</dt>
              <dd>{alert.equipmentId}</dd>
            </div>
            <div>
              <dt>Zone</dt>
              <dd>{zone ? `${zone.code} · ${zone.name}` : alert.zoneId}</dd>
            </div>
            <div>
              <dt>Grid reference</dt>
              <dd>{zone ? `${gridRef(zone.centroid)} · ${zone.hall}` : '—'}</dd>
            </div>
            <div>
              <dt>Category</dt>
              <dd>{typeDefinition.category}</dd>
            </div>
            <div>
              <dt>Severity</dt>
              <dd>{SEVERITY_META[alert.severity].title}</dd>
            </div>
            <div>
              <dt>Detection</dt>
              <dd>{DETECTION_LABEL[alert.source]}</dd>
            </div>
            <div>
              <dt>Confidence</dt>
              <dd>
                <span className="confidence">
                  <span className="confidence__bar" aria-hidden="true">
                    <span style={{ width: `${Math.round(alert.confidence * 100)}%` }} />
                  </span>
                  <span className="num">{formatConfidence(alert.confidence)}</span>
                </span>
              </dd>
            </div>
            <div className="detail-grid__wide">
              <dt>Timestamp</dt>
              <dd className="num">
                {formatDate(alert.timestamp)} · {formatTime(alert.timestamp)}
              </dd>
            </div>
          </dl>

          <h3 className="drawer__section">Sensor data</h3>
          <div className="table-wrap">
            <table className="sensor-table">
              <thead>
                <tr>
                  <th scope="col">Signal</th>
                  <th scope="col">Value</th>
                  <th scope="col">Expected</th>
                </tr>
              </thead>
              <tbody>
                {alert.sensorData.map((reading) => (
                  <tr key={reading.label} data-out={reading.outOfRange || undefined}>
                    <th scope="row">{reading.label}</th>
                    <td className="num">
                      {reading.outOfRange && (
                        <span className="out-flag" aria-label="Out of range">
                          ▲
                        </span>
                      )}
                      {reading.value}
                    </td>
                    <td className="num">{reading.expected ?? '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <h3 className="drawer__section">Suggested action</h3>
          <p className="suggested">{alert.suggestedAction}</p>

          <h3 className="drawer__section">Event log</h3>
          <ol className="timeline">
            <li>
              <span className="num">{formatTime(alert.timestamp)}</span>
              <span>Alert raised · {DETECTION_LABEL[alert.source]}</span>
            </li>
            {alert.acknowledgedAt && (
              <li data-ack>
                <span className="num">{formatTime(alert.acknowledgedAt)}</span>
                <span>Acknowledged by operator</span>
              </li>
            )}
          </ol>
        </div>

        <footer className="drawer__foot">
          <button
            type="button"
            className="btn btn--primary"
            onClick={() => onAcknowledge(alert.id)}
            disabled={alert.acknowledged}
          >
            {alert.acknowledged ? (
              <>
                <IconCheck size={18} />
                Acknowledged
              </>
            ) : (
              'Acknowledge'
            )}
          </button>
          <button type="button" className="btn" onClick={() => onShowOnMap(alert.id)}>
            <IconTarget size={18} />
            Show on map
          </button>
          <button type="button" className="btn btn--ghost" onClick={onClose}>
            Close
          </button>
        </footer>
      </aside>
    </div>
  );
}
